---
galaxy_info:
  author: René Moser
  company: Moser Systems
  license: MIT
  min_ansible_version: 1.4

  platforms:
  - name: EL
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - system

dependencies: []
