---
- name: 1.Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
 
- name: 2.Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
 
- name: 3.Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists

- name: EPEL
  yum:
    name: epel-release
    state: latest
  
- name: 4. Install common apps
  yum:
    name: htop,rsync,screen,tmux,iftop,iotop,nano,git,wget,unzip,mc
    state: latest
  
- selinux:
    state: disabled
    