---
galaxy_info:
  author: Jeff Widman
  description: Installs and configures yum-cron
  company: RockClimbing.com

  license: MIT
  min_ansible_version: 1.9

  platforms:
  - name: EL
    versions:
     - 7

  categories:
  - packaging
  - system

dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
